name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setting up PHP
        uses: ./.github/actions/php

      - name: Installing Composer
        run: |
          composer install --dev --no-ansi --no-interaction --no-suggest --prefer-dist

      - name: Running PHPInsights
        run: ./vendor/bin/phpinsights --no-interaction --min-quality=85 --min-architecture=85 --min-style=85

      - name: Running PHPStan
        run: ./vendor/bin/phpstan analyse src tests

      - name: Running PHPUnit
        run: ./vendor/bin/phpunit tests/
